#!/bin/bash

## init PHP
(cd public/php && composer install)

## init Python
#(cd python && virtualenv venv && source venv/bin/activate && pip install --allow-external -r requirements.txt)

## http://www.pindi.us/blog/automating-pip-and-virtualenv-shell-scripts
if [ ! -d "python/venv" ]; then
    virtualenv -q python/venv --no-site-packages
    echo "Virtualenv created."
fi

if [ ! -f "python/venv/updated" -o python/requirements.pip -nt python/venv/updated ]; then
    (cd python && virtualenv venv && source venv/bin/activate && pip install -r python/requirements.pip && touch venv/updated) && echo "Requirements updated."
fi
